spring.application.name=coinpilot
spring.datasource.url=jdbc:postgresql://localhost:5432/coinpilot
spring.datasource.username=postgres
spring.datasource.password=666999
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jackson.default-property-inclusion=non_null